PROJECT:
  PROJECT_NAME: "cad-alexnet-classification"

DATA:
  LOCAL_ROOT_DIR: "file://data/raw"
  LOCAL_OUTPUT_DIR: "file://results/"
  EVAL_DIR: "data/raw/valid"

  S3_BUCKET: "cad-brbh-datascience"
  S3_INPUT_DIR: "s3://cad-brbh-datascience/alexnet_image_classification/"
  S3_TRAIN_DIR: "s3://cad-brbh-datascience/alexnet_image_classification/data/full/train/"
  S3_VAL_DIR: "s3://cad-brbh-datascience/alexnet_image_classification/data/full/valid/"
  S3_CHECKPOINT_DIR: "s3://cad-brbh-datascience/alexnet_image_classification/checkpoints"
  S3_OUTPUT_DIR: "s3://cad-brbh-datascience/alexnet_image_classification/models"

MODEL:
  NUM_CLASSES: 10
  RESIZE: 224

TRAINING:
  EPOCHS: 100
  BATCH_SIZE: 128
  LEARNING_RATE: 0.0005

OPTIMIZER:
  OPTIMIZER: "SGD"
  WEIGHT_DECAY: 0.00001
  SGD_MOMENTUM: 0.9

AUGMENTATION:
  AUGMENTATION_TRANSFORMATIONS:
    p: 0.2
    shift_limit: 0.05
    scale_limit: 0.05
    rotate_limit: 15
    border_mode: "constant"